### ISSUE TITLE
build with otp19.3 failed

### ISSUE THREAD

**Issue by lanbai1993** [vernemq/vernemq#1858]
since set up from docker failed seeing issue Can't open /lib/env.sh
#1857, 
i want to build from source git@github.com:vernemq/vernemq.git, 
and i build with Erlang OTP 19.3 for mac osx.

**xiewei@xw vernemq % make rel**
cat vars.config > vars.generated
echo "{app_version, \"1.12.1-1-gdb19fc9\"}." >> vars.generated
/Users/xiewei/tools/vernemq/rebar3  release

=ERROR REPORT==== 1-Aug-2021::18:20:06 ===
beam/beam_load.c(1287): Error loading module rebar3:
  mandatory chunk of type 'Atom' not found

=ERROR REPORT==== 1-Aug-2021::18:20:06 ===
Loading of /Users/xiewei/tools/vernemq/rebar3/rebar/ebin/rebar3.beam failed: badfile
escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 760)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
make: *** [rel] Error 127

======================
hi can you give suggestion to solve this?

osx version is 11.3.1 (20E241). it seems the otp support only now with 10.10.  how to do this?

**Comment by ioolkos** [comment]
@lanbai1993 can you try building with OTP 22 or 23?
This is probably due to the `rebar3` version used, which is built for 22-24. (so, probably I should tag OTP 22 as a minimum build version)

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages (.deb/.rpm/Docker) requires a subscription.
